### ISSUE TITLE
Possibility to make tertiary factory to appear alongside secondary factory in cities. 

### ISSUE THREAD

**Issue by Limyx826** [2TallTyler/improved_town_industries#101]
In my current map of 512 x 512 with a setting of normal no. of towns and 1/4 cities with Renewed Village Growth game script. There were like 2-3 of a type of secondary industry (i.e. Food Processing Plant, Steel Mill, Sawmill, Oil Refinery, Paper Mill I ain't sure this count as tertiary or secondary) across the map and 1 of a single type of tertiary industry (i.e. Building Materials Factory, Goods Factory). I believe this happen due to the requirement of secondary industries required city status and the low number of cities in a single map.

Attached are the mini map showing the number of industries. 
![Screenshot 2023-03-18 011849](https://user-images.githubusercontent.com/38696851/228775339-7d5f5e3d-12a9-4c48-93c6-432238201e15.png)

If possible that those tertiary industries can shows up in the same city as secondary industries, then there will be more options to transport cargo to. Perhaps this can be a parameter for people who wish for this option. Maybe another for same parameter that eliminates the city requirement for secondary industry.

**Comment by 2TallTyler** [comment]
Hello! Sorry for the super late response. 

This restriction is intentional, to avoid the player building all their industries in one city, and only ever having to grow and provide transport services in that one city.

I don't plan to change this. You would just need more cities to fit all your secondary industries. 😉

**Comment by Limyx826** [comment]
Understandable, it just that your grf ain't suitable on small map on 1/4 city setting. I just get around this by double the size of map.
