### ISSUE TITLE
Towns do not produce waste with ITL Houses in 14.0-beta3

### ISSUE THREAD

**Issue by jdcaperon** [2TallTyler/improved_town_industries#108]
Not sure whether this is related to ITL houses or ITI, so I'm raising it here. Towns do not produce waste in 14.0-beta3 or 14.0 in general afaict. I reverted to 13.4 and all is well.

**Comment by 2TallTyler** [comment]
OpenTTD 14.0 changes how towns produce cargo, breaking the undefined behavior that ITI previously relied on. Luckily, it adds a new way to properly define this behavior, which I added a few hours ago and released as ITI 2.9. Let me know if that works for you!

**Comment by jdcaperon** [comment]
Fixed thank you sir!
