### ISSUE TITLE
Fatal error at startup

### ISSUE THREAD

**Issue by Fauleresel** [2TallTyler/improved_town_industries#109]
Error message says :
![Bildschirmfoto_2024-02-15_10-40-53](https://github.com/2TallTyler/improved_town_industries/assets/129102009/4aba0bc4-8e38-489b-964a-a31eb3563b90)

**Comment by James103** [comment]
Do you get the same error
a) with default OpenGFX graphics?
b) with Improved Town Houses also loaded?

**Comment by Fauleresel** [comment]
The nml says:

/* Create an error if OpenTTD version is before 14.0 (required for town_production_effect property) */
if (version_openttd(14,0) > openttd_version) {
	error(FATAL, string(STR_ERROR_GAME_VERSION));
}



It works with 14.0 beta. 
Maybe you could mention that somewhere, I guess you can close the issue.

**Comment by 2TallTyler** [comment]
That error in NML is supposed to show you a descriptive error instead of what you reported. I guess I coded it wrong. 😄 

I will leave this open until I figure out how to do the error properly. Thanks for the report!

**Comment by 2TallTyler** [comment]
Strings fixed in #112.
