### ISSUE TITLE
Banks seem to be satisified forever (not giving money)

### ISSUE THREAD

**Issue by Salmakis** [2TallTyler/improved_town_industries#117]
After a while, Banks still accept valuables but they are not paying any money (like when a factory got 65535 of a good).
Also the value is not calculated for the game script "Renewed village growth" so growing a city then is not possible anymore.

not 100% sure if its this is the right repo for that issue.

**Comment by 2TallTyler** [comment]
Thanks for the report! Please try out 2.11, on Bananas momentarily, and let me know if the problem persists.

**Comment by 2TallTyler** [comment]
Er, make that 2.12, I made a silly mistake and created an infinite loop. 😅
