### ISSUE TITLE
FIRS 2 and ECS are not listed as incompatible with Improved Town Industries.

### ISSUE THREAD

**Issue by James103** [2TallTyler/improved_town_industries#14]
NewGRF version: b53a0deccb0b9b1867a1fe3f11989c60e60b13a4

Did you forget about the following industry sets being incompatible?
* FIRS 2 (GRFID F1250006)
* ECS Vectors (GRFID 4D656Fxx)
* Extreme Industry Set

**Comment by 2TallTyler** [comment]
Yep. I couldn't find FIRS 2 and XIS wasn't out yet, but I did forget ECS Vectors. Thanks!
