### ISSUE TITLE
Untranslated strings for both Improved Town* NewGRFs

### ISSUE THREAD

**Issue by James103** [2TallTyler/improved_town_industries#2]
## Versions used
OpenTTD: 1.10.2
NewGRF:
```
54540301|1899C0EE609AFD837091F9BF9E64CEE2|improved_town_layouts-1.1.2\improved_town_layouts.grf = 0 0 1 1 1
54540401|2B9CD4A272177B792F2E68BA43C254B9|improved_town_industries-1.0.0\improved_town_industries.grf = 0 1 1 0
```

## Expected result
The strings corresponding to the different industries and houses are translated correctly (in line with the base game).

## Actual result
The strings corresponding to the different industries and houses are not translated at all.

## Steps to Reproduce.
1. Do not use any NewGRFs.
2. Generate a new map.
3. Set language to non-English, such as Chinese or Spanish.
4. Observe that industry and town building names are translated.
5. Use the above NewGRFs.
6. Generate a new map.
7. Set language to non-English, such as Chinese or Spanish.
8. Observe that industry and town building names are not translated.

**Comment by 2TallTyler** [comment]
NMLC gave me errors when I tried using built-in TTD strings with ITL so I defined my own. But it’s worth another try at using the default strings for better translations. Thanks.

**Comment by James103** [comment]
Would it be possible to fetch the translations for the required strings from the OpenTTD main repository and copy them over into the NewGRF, as a workaround to directly using OpenTTD's built-in strings?
