### ISSUE TITLE
Most primary industries can't be generated, prospected, built, or funded.

### ISSUE THREAD

**Issue by James103** [2TallTyler/improved_town_industries#3]
## Versions used
OpenTTD: 1.10.2
NewGRF:
```
54540301|1899C0EE609AFD837091F9BF9E64CEE2|improved_town_layouts-1.1.2\improved_town_layouts.grf = 0 0 1 1 1
54540401|2B9CD4A272177B792F2E68BA43C254B9|improved_town_industries-1.0.0\improved_town_industries.grf = 0 1 1 0
```

## Expected result
* Coal mines can be generated, prospected, built, and funded, in both scenario editor and normal gameplay.
* Farms can be generated, prospected, built, and funded, in both scenario editor and normal gameplay.
* Logging Camps can be generated, prospected, built, and funded, in both scenario editor and normal gameplay.
* Iron Ore Mines can be generated, prospected, built, and funded, in both scenario editor and normal gameplay.
* Oil Wells can be generated, prospected, built, and funded, in both scenario editor and normal gameplay.

## Actual result
* Coal mines can't be generated, prospected, built, or funded, not even in the scenario editor. Attempting to build one yields an error message with subtitle of "Farm" (see #1), and all attempts of prospecting fail (you could burn through trillions of in-game currency that way to no avail).
* Farms can be generated and prospected, but not built or funded (even in scenario editor). However, after 192 farms per million tiles, all attempts of prospecting fail.
* Logging Camps can be generated and prospected, but not built or funded (even in scenario editor). However, after 96 logging camps per million tiles, all attempts of prospecting fail.
* Iron Ore Mines can be generated and prospected, but not built or funded (even in scenario editor). However, after 96 iron mines per million tiles, all attempts of prospecting fail.
* Oil Wells can be generated, prospected, built, and funded by the player, but after 128 oil wells per million tiles, all attempts of prospecting fail (though you can still manually build more).
The industry density counts were taken from default settings (where "Industry Density" is Normal).

## Steps to reproduce:
1. Load the above NewGRFs with default settings (Industry Density is Normal).
2. Set a map size of 1024 x 1024.
3. Start a new game (or load into the scenario editor).
4. Make sure that there is at least one town.
5. If you are in normal gameplay, give yourself a few dozen million of in-game currency.
6. Attempt to generate, prospect, build, or fund the above industries.
7. Observe what happens to the industry counts (some of them cap out and others don't generate at all).
8. Load into the scenario editor without any NewGRFs.
9. Make sure that there is at least one town.
10. Attempt to generate, prospect, build, or fund the above industries.
11. Observe what happens to the industry counts (all of them increase until the map is filled with industries).

**Comment by 2TallTyler** [comment]
Do you have the option to prospect logging camps? They're coded as processing industries to enable the sub-tropical tree-cutting behavior and therefore are funded, not prospected. That's what I see, at least.

**Comment by James103** [comment]
Even though logging camps (and some other industries) are classed as processing industries (meaning they are funded, not prospected), the industry generation step during world generation (which can be run using "Many random industries" in the scenario editor) overrides this and builds the industry in a random location (as if you prospected the industry). Since this is different and goes by different rules, the number of logging camps funded this way can't exceed 96 per million tiles on normal density.

**Comment by 2TallTyler** [comment]
Thanks. I will remove the "Many random industries" build limit in the scenario editor for all industries.
