### ISSUE TITLE
Delay Nuclear Waste production

### ISSUE THREAD

**Issue by 2TallTyler** [2TallTyler/improved_town_industries#33]
Delaying the Nuclear Power Plant's conversion of Nuclear Fuel to Nuclear Waste would encourage use of separate waste trains from the fuel supply chain, an important gameplay objective.

**Comment by James103** [comment]
ECS delays Tourist production with the Tourist Center using some of the industry's persistent storage and rotating the deliveries through this persistent storage monthly. Is that how you would accomplish that or is there some other way?

**Comment by 2TallTyler** [comment]
That was my plan, yes. Thanks for the code suggestion though, I'll see if I can find the ECS source code.

**Comment by 2TallTyler** [comment]
I don't plan to implement this after all. ITI is designed as a simple, minimalist industry set, and this mechanic is too complex to fit in with that ethos.
