### ISSUE TITLE
Industry Chain View Passenger cargo issue

### ISSUE THREAD

**Issue by Limyx826** [2TallTyler/improved_town_industries#37]
Since you added passenger as a valid cargo to virtually all industries in your newGRF, there a bit confusion when viewing the industries chain as it show all industries in the windows making it hard to determine where the other cargoes supposed to go. 

Since I always uses the minimap to determine where the industry is when looking for a certain chain, it is possible to hide only the passenger in the industry chain?

![image](https://user-images.githubusercontent.com/38696851/95674923-11908680-0be6-11eb-89b0-cebca67622a4.png)
When shown in the industry chain

![image](https://user-images.githubusercontent.com/38696851/95674951-48ff3300-0be6-11eb-99aa-435fd2d50eb9.png)
When linked to the minimap

**Comment by 2TallTyler** [comment]
Thanks for the report. I've been unhappy with this too, and have fixed it in 1.6.0 (currently in beta, you can try it out from the releases page on this GitHub repo). Industry tiles still accept passengers, but they're not listed as a required cargo. The production of passengers is also changed from a random production level to match the cargo delivered — .25 passengers per every ton delivered. Feel free to test and let me know your thoughts, ideally before the public release around the end of October. 😀

**Comment by Limyx826** [comment]
Ok👍, not a problem.
