### ISSUE TITLE
Waste chart seems wrong

### ISSUE THREAD

**Issue by Limyx826** [2TallTyler/improved_town_industries#38]
I noticed something weird when checking on the industry chain for 1.6 beta. The waste chain seem very weird, isn't houses supposed to produced it but it seem like house are accepting waste. In gameplay it was correct, the houses are supplying waste. 

![image](https://user-images.githubusercontent.com/38696851/95882075-d9d33b80-0dab-11eb-849c-1d91fb759a57.png)

![image](https://user-images.githubusercontent.com/38696851/95882273-143cd880-0dac-11eb-8fa1-c72acfd938df.png)

**Comment by Limyx826** [comment]
Also is farm suppose to accept waste or recycled materials or both?

**Comment by 2TallTyler** [comment]
The Farm accepts both. Waste is household garbage to be fed to the pigs (which was as gross as it sounds), while Recycled Materials is compost for the field.

Do you have any other NewGRFs loaded (houses especially)? Using just Improved Town Layouts, houses don't appear as a destination.

![waste](https://user-images.githubusercontent.com/55058389/95883092-81b71d80-0d48-11eb-8724-6fb2204228a5.png)

**Comment by Limyx826** [comment]
Here's my list of NewGRFs
![image](https://user-images.githubusercontent.com/38696851/95884974-561b4e00-0daf-11eb-9d97-5a415b8023ff.png)

**Comment by Limyx826** [comment]
Seem like it has no impact on the gameplay I guess this can be closed now

**Comment by 2TallTyler** [comment]
Thanks. Waste uses the same cargo ID as Paper in the original game, so if UK Houses Early Mod uses legacy IDs and not the modern cargolabel WSTE, it could be mistakenly accepting Waste. I don't know why any of its houses would accept Paper, though.

Seems like a non-issue for now. Thanks for the report, anyway!
