### ISSUE TITLE
The "Generate Primary Industries Only" setting affects the ability to player-fund secondary industries.

### ISSUE THREAD

**Issue by James103** [2TallTyler/improved_town_industries#4]
## Versions used
OpenTTD: 1.10.2
NewGRF:
```
54540301|1899C0EE609AFD837091F9BF9E64CEE2|improved_town_layouts-1.1.2\improved_town_layouts.grf = 0 0 1 1 1
54540401|2B9CD4A272177B792F2E68BA43C254B9|improved_town_industries-1.0.0\improved_town_industries.grf = 2 1 1 1
```

## Expected result
Turning on "Generate Primary Industries Only" should only turn off the automatic generation of secondary industries. It should not affect the ability to manually fund these industries.
![image](https://user-images.githubusercontent.com/37945304/87676998-e0b3c900-c73e-11ea-833c-c6787e51eccc.png)

## Actual result
Turning on "Generate Primary Industries Only" not only turns off automatic generation of secondary industries, but also makes you unable to fund these industries yourself.
![image](https://user-images.githubusercontent.com/37945304/87677125-00e38800-c73f-11ea-94df-42c89dee127e.png)

## Steps to Reproduce
1. Load the above NewGRFs with default settings.
2. Turn on "Generate Primary Industries Only"
3. Start a new map.
4. Check each industry in the "Fund new industry" list to see if it can be player-funded.

**Comment by 2TallTyler** [comment]
I think this is related to #3 but will find out.
