### ISSUE TITLE
Typo in comment for iron_mine.nml

### ISSUE THREAD

**Issue by James103** [2TallTyler/improved_town_industries#40]
## NewGRF Version
dc82c716c90b22d5e172ec0305ccc33552e00eba

## Expected Result
The comment reads:
> Check if an even number **of iron** mines already exist on the map (0 is even) by dividing by 2 and checking for a remainder. If even, build without needing cluster. If odd, continue to next switch for clustering
## Actual Result
The comment reads:
> Check if an even number **ofironl** mines already exist on the map (0 is even) by dividing by 2 and checking for a remainder. If even, build without needing cluster. If odd, continue to next switch for clustering
## Relevant Code
https://github.com/2TallTyler/improved_town_industries/blob/dc82c716c90b22d5e172ec0305ccc33552e00eba/src/iron_mine.nml#L87

**Comment by 2TallTyler** [comment]
Thanks!

Closed by https://github.com/2TallTyler/improved_town_industries/commit/532a7ce3cf9bcea7bdc809a08d258b7075b7538f
