### ISSUE TITLE
Adjust industry funding costs

### ISSUE THREAD

**Issue by 2TallTyler** [2TallTyler/improved_town_industries#56]
These are still using placeholder values, but should be made more interesting for "industry tycoon" gameplay, particularly when using "generate primary industries only".

It may be helpful to look at other games here, like Railroad Tycoon 3 and Railway Empire.

**Comment by James103** [comment]
For example, you could make it so (not all has to be implemented):
* More technologically advanced industry chains are more expensive to set up, meaning that Nuclear Fuel plants are more expensive than Steel Mills and Oil Refineries, which in turn are more expensive than Sawmills and Farms. Factories could fall in the middle of this spectrum.
* Industry chains that give more profit are more expensive (and/or riskier or more complex) to set up to compensate for the increased revenue.

**Comment by 2TallTyler** [comment]
Totally agree with both of your points.

**Comment by 2TallTyler** [comment]
From the changelog:
- Change: Rebalanced industry funding costs
  - Sawmills are the cheapest industry to fund, possible to fund with a standard £300k starting loan in addition to an initial train line (Iron Horse 2)
  - Power Plants are another good starting industry, only slightly more expensive than the Sawmill and accepting either Coal or Oil (or Waste, when enabled).
  - Recycling Centers are relatively inexpensive but are not a good starting industry since small towns won't produce much Waste.
  - The Factory is the standard Goods origin and isn't affordable with the starting loan, but won't be too hard to save up for.
  - The Paper Mill also produces Goods, but unlike the Factory it accepts Wood directly without needing a Sawmill or Steel Mill. This benefit, and the complexity of paper-making, makes it more expensive than the Factory.
  - Steel Mills and Oil Refineries are an impressive industries and an expensive investment.
  - Nuclear Fuel Plants are high-tech and quite pricey.
- Change: Rebalanced cargo payment rates to new industry funding costs
  - Reduced payments for primary and secondary bulk cargos: Wood, Oil, Uranium, Lumber, Steel, Waste
  - Increased payment for Chemicals
  - Reduced payment for Goods, but reduced its rate of cargo decay. 
    - Note that Food has a much quicker decay rate. On journeys longer than ~81 days, it's now more profitable to send Food to factories to be processed into Goods. Yummy preservatives! (and two delivery payments!)
  - Increased payment for Mail, but also increased cargo decay. This is mostly because I forget about Mail, and want to incentivize not forgetting about it.
  - Significantly increased payment for Passengers, to compensate for smaller towns with Improved Town Layouts.
