### ISSUE TITLE
Oil Rigs do not spawn on map generation

### ISSUE THREAD

**Issue by A-mak88** [2TallTyler/improved_town_industries#60]
No matter what year (tested year 2200) oil rigs do not spawn during map generation and also cannot be funded in-game.

looking at source for oil rigs they are disabled behind /* comment tags? I am not sure if this is intended behavior as I am just learning.

**Comment by 2TallTyler** [comment]
Thanks for the report!

This industry set uses base game Oil Rigs, controlled by the first (uncommented) if statement. The commented-out industry definition was an attempt to define it myself, but there isn't a way to access the "Maximum distance from edge for Oil industries" setting with a custom industry and Oil Rigs were spawning in small ponds throughout the map. I commented out my custom industry to use the base game industry, which worked, but then I forgot to remove that code.

Base game Oil Rigs do not spawn during map generation. They only appear later in game. They also cannot be funded unless "Manual primary industry construction method" is set to "Prospecting" or "As other industries".

I have now removed the unnecessary code and added comments explaining how this works.
