### ISSUE TITLE
Consolidate STR_FUND_AVAILABLE_* strings into a single string

### ISSUE THREAD

**Issue by James103** [2TallTyler/improved_town_industries#63]
https://github.com/2TallTyler/improved_town_industries/blob/673754e1527e0243e2618c080cc7622c140914d4/src/lang/english.lng#L30-L37
Could this be replaced with just a single line of the following?
```
STR_FUND_AVAILABLE					:{BLACK}Introduced: {YELLOW}{NUM}
```
This would mean using for example `string(STR_FUND_AVAILABLE, 1800);` instead of `string(STR_FUND_AVAILABLE_1800);` and likewise elsewhere where `STR_FUND_AVAILABLE_*` occurs.

**Comment by 2TallTyler** [comment]
Thanks for the suggestion. Always good to make translating less of a burden.

{NUM} doesn't seem to be a supported string parameter, but a literal string is fine.
