### ISSUE TITLE
Translators: Two new strings added

### ISSUE THREAD

**Issue by 2TallTyler** [2TallTyler/improved_town_industries#65]
Hello translators, @AviationGamerX, @arikover, @WoelfiVW, @mknart:

I have added a new feature (f9e2ace) which includes two new strings. If you would be willing to update your translations and submit PRs, it would be much appreciated.

> STR_PARAM_NAME_INDUSTRY_POP         :Population requirement for secondary industries
> STR_PARAM_DESC_INDUSTRY_POP         :The minimum town population required per secondary industry.{}{}The default value of 300 is optimized for Improved Town Layouts, where towns generate with low population. If using another house set, this should be increased to at least 1,000.{}{}Note: Before 1850, the requirement is 1/3 of this number.

This NewGRF is not in active development anymore, so this shouldn't be a frequent occurrence.

I plan to release 1.7.3 with these changes (and the new Swedish translation) on April 1st to coincide with the release of OpenTTD 1.11.0.

Thanks!

Tyler

**Comment by James103** [comment]
Translations that still need work:
* [ ] `arabic.lng`
* [x] `english.lng`
* [x] `french.lng`
* [ ] `german.lng`
* [x] `swedish.lng`

**Comment by AviationGamerX** [comment]
I trandlated but for some reason it didn't make the PR :(
I will redo them soon today.

**Comment by 2TallTyler** [comment]
Closed by #66, #67, #68, and #69.
