### ISSUE TITLE
Only coal mines and factories are generated

### ISSUE THREAD

**Issue by wopian** [2TallTyler/improved_town_industries#75]
Recently discovered this newGRF (and ITL), however the latest version (1.7.5) on BaNaNaS appears to be completely broken on temperate climates.

With only ITI and ITL enabled, only coal mines and factories are generated in a new game (screenshot is a 1700 start so no built factories yet, new games after 1800 just have coal/factories too)

![image](https://user-images.githubusercontent.com/3440094/119245196-392dd100-bb6f-11eb-9a89-c764edd748be.png)

Edit: the BaNaNaS Improved Towns Industries [1.7.5 release](https://bananas.openttd.org/package/newgrf/54540401/2021-05-22T14:45:01+00:00) has the title of "Improved Town Industries 1.7.4 tropic alpha", so looks like the [`subtropics`](https://github.com/2TallTyler/improved_town_industries/tree/subtropic) branch may have been what was deployed as 1.7.5 on BaNaNaS

![image](https://user-images.githubusercontent.com/3440094/119245251-9a55a480-bb6f-11eb-872e-605a1203ae41.png)

Edit 2: The subtropical climate works as intended so definitely a mix-up of the wrong branch being built.

**Comment by James103** [comment]
Can you try checking the "Fund new industries" list of industry types as well?

Assuming the bug is in effect, you should see just "Factory" if manual primary industry construction is set to "None", or just "Factory" and "Coal Mine" otherwise.

**Comment by wopian** [comment]
> Can you try checking the "Fund new industries" list of industry types as well?

Only coal mines and factories are listed.

> Assuming the bug is in effect, you should see just "Factory" if manual primary industry construction is set to "None", or just "Factory" and "Coal Mine" otherwise.

Same as above, regardless of setting.

> Also try opening the "Industry chains" window then holding left click on "Select Industry", then observing the contents of the resulting dropdown.

![image](https://user-images.githubusercontent.com/3440094/119245355-92e2cb00-bb70-11eb-830d-1333927457eb.png)

**Comment by James103** [comment]
In other words, somehow using the industry set in the Temperate climate means that only Coal Mine and Factory exists and is defined for the current game.

**Comment by 2TallTyler** [comment]
Thanks for the report. Yes, it seems I accidentally uploaded the tropic beta. It's fixed now — BaNaNaS doesn't let me upload another version of 1.7.5 so I bumped it to 1.7.6.

**Comment by wopian** [comment]
No problem 👍
