### ISSUE TITLE
Translation update: Arabic

### ISSUE THREAD

**Issue by 2TallTyler** [2TallTyler/improved_town_industries#81]
Hello @AviationGamerX !

I've released Version 2 of Improved Town Industries, with a lot of new strings. Would you be willing to update your translation?

Thanks!

Tyler

**Comment by AviationGamerX** [comment]
Yes, but I will hopefully be avilable after 18th may, so if you're willing to realease it early go ahead, I will do it when I can and you can update it in the next update.

**Comment by 2TallTyler** [comment]
That's fine, I can wait until then! Thanks!

**Comment by AviationGamerX** [comment]
oh god, sorry I forgot about that, I feel so sorry, :(
I'll do it asap, never ever wait for me again lol.

**Comment by 2TallTyler** [comment]
You'll need to either open a Pull Request or just send me the language file - I don't currently have it. :)

**Comment by AviationGamerX** [comment]
oh what, but I did it all and sent it, did not work?
I hope it didn't just delete everything 😞.
I will look again into it, not sure why it didn't work.

**Comment by AviationGamerX** [comment]
oh found it nvm lol, all done now :D
