### ISSUE TITLE
Translation update: Czech

### ISSUE THREAD

**Issue by 2TallTyler** [2TallTyler/improved_town_industries#83]
Hello @adpro!

I've released Version 2 of Improved Town Industries, with a lot of new strings. Would you be willing to update your translation?

Thanks!

Tyler

**Comment by adpro** [comment]
Thank you @2TallTyler for notification. I am busy IRL, but I will try to gradually update the translation and then send PR.

**Comment by adpro** [comment]
Hello @2TallTyler ,
I finally got enough time to update the Czech translation. There was not enough time in the last months, many necessary events and obligations in IRL.
Actual output is PR https://github.com/2TallTyler/improved_town_industries/pull/95
