### ISSUE TITLE
Waste Being Picked Up From Recycling Center Station (?)

### ISSUE THREAD

**Issue by benjamin-kirkbride** [2TallTyler/improved_town_industries#99]
Not exactly sure what is happening here, but it doesn't seem right:

![image](https://user-images.githubusercontent.com/3373830/222017234-a7e938a2-e9a0-4b70-8270-2b481efc2d97.png)

Seems like since the station is close to the town, the goods are being put in the station, then the vehicles are picking it up and taking it away ? Do I need to put a vehicle on a loop to just pick-up the waste from the station and dump it right back in?

**Comment by benjamin-kirkbride** [comment]
It seems like you can't deposit goods you get from a station back into itself, even if it technically accepts said good. Not sure what the intended work-around is.

**Comment by 2TallTyler** [comment]
The intended workaround is an "Unload and leave empty" on all vehicles dropping off Waste. Vehicles cannot drop off cargo at the station where it originated. 🙂
